name: CI

on:
  push:
    branches:
      - master

jobs:
  test-and-build:
    runs-on: self-hosted

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Run unit tests
        run: |
          npm run test > test-report.txt || echo "Tests failed" > test-report.txt

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: test-report.txt

      - name: Install Docker Engine
        uses: docker/setup-buildx-action@v2
        with:
          version: 'latest'

      - name: Docker logins
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Set Version with date-time
      #   run: |
      #     TIMESTAMP=$(date +'%Y%m%d%H%M%S')
      #     VERSION="v${TIMESTAMP}_${RANDOM}"
      #     echo "APP_VERSION=$VERSION" >> $GITHUB_ENV


      - name: Build the Docker image
        env:
          username: ${{ secrets.DOCKER_USERNAME }}
          image_name: new-image
          version: 1.0.0
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/$image_name:$version .

      - name: upload artifact for the image
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: ./
          

      - name: Push the Docker image
        env:
          username: ${{ secrets.DOCKER_USERNAME }}
          image_name: new-image
          version: 1.0.0
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/$image_name:$version

  Deploy:
    name: Run image as a container
    runs-on: self-hosted
    needs: test-and-build # This job depends on the previous one
    env:
      username: ${{ secrets.DOCKER_USERNAME }}
      image_name: new-image
      version: 1.0.0

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image
          path: ./

      - name: Run the container
        env:
          username: ${{ secrets.DOCKER_USERNAME }}
          image_name: new-image
          version: 1.0.0
        run: |
          docker run -d -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/$image_name:$version