name: CI

on:
  push:
    branches:
      - master

jobs:
  test-and-build:
    runs-on: self-hosted

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Run unit tests
        run: |
          npm run test > test-report.txt || echo "Tests failed" > test-report.txt

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: test-report.txt

      - name: Install Docker Engine
        uses: docker/setup-buildx-action@v2
        with:
          version: 'latest'

      - name: Docker logins
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set Version with date-time
        run: |
          DATE=$(date +%Y%m%d)
          TIME=$(date +%H%M%S)
          VERSION="1.0.0-${DATE}.${TIME}"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Docker image version: $VERSION"

      - name: Build the Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/new-image:$VERSION .

      - name: Push the Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/new-image:$VERSION

  Deploy:
    name: Run image as a container
    runs-on: self-hosted
    needs: test-and-build # This job depends on the previous one
    steps:
      - name: Download artifact for deployment
        uses: actions/download-artifact@v4
        with:
          name: test-report
          path: .
      - name: Run the image as a container
        run: |
          echo "running container with the image: ${{ secrets.DOCKER_USERNAME }}/new-image:${{ needs.test-and-build.outputs.VERSION }}"
          docker run -d -p 3001:3000 ${{ secrets.DOCKER_USERNAME }}/new-image:${{ needs.test-and-build.outputs.VERSION }}
    